package com.example.theater.controller;

import com.example.theater.config.Database;
import com.example.theater.util.*;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.node.*;
import com.sun.net.httpserver.*;
import java.io.*; import java.net.*; import java.nio.charset.StandardCharsets; import java.sql.*; import java.time.*; import java.util.*; import java.util.concurrent.*;

public class ApiServer {
 private final HttpServer server; private final Map<String,Session> sessions=new ConcurrentHashMap<>();
 record Session(long userId,String role,String name){}
 public ApiServer(int port)throws IOException{ server=HttpServer.create(new InetSocketAddress(port),0); server.createContext("/api/",this::handle); server.createContext("/",this::staticFile); server.setExecutor(Executors.newCachedThreadPool());}
 public void start(){System.out.println("Theater app: http://localhost:8080"); server.start();}
 private void handle(HttpExchange e){
  try { dispatch(e); } catch(Exception ex){send(e,500,Json.error("Server error. Check the console log.")); ex.printStackTrace();}
 }
 private void dispatch(HttpExchange e)throws Exception{
  String path=e.getRequestURI().getPath(), method=e.getRequestMethod();
  JsonNode body=Json.M.createObjectNode();
  if(method.equals("POST")){byte[] b=e.getRequestBody().readAllBytes(); if(b.length>0)body=Json.M.readTree(new String(b,StandardCharsets.UTF_8));}
  if(path.equals("/api/auth/register")&&method.equals("POST")){register(e,body);return;}
  if(path.equals("/api/auth/login")&&method.equals("POST")){login(e,body);return;}
  if(path.equals("/api/auth/logout")&&method.equals("POST")){logout(e);return;}
  if(path.equals("/api/movies")&&method.equals("GET")){movies(e);return;}
  if(path.matches("/api/movies/\\d+/shows")&&method.equals("GET")){shows(e,Long.parseLong(path.split("/")[3]));return;}
  if(path.matches("/api/shows/\\d+/seats")&&method.equals("GET")){seats(e,Long.parseLong(path.split("/")[3]));return;}
  if(path.equals("/api/bookings")&&method.equals("POST")){createBooking(e,body);return;}
  if(path.equals("/api/bookings")&&method.equals("GET")){bookings(e);return;}
  if(path.matches("/api/bookings/\\d+/cancel")&&method.equals("POST")){cancel(e,Long.parseLong(path.split("/")[3]));return;}
  if(path.equals("/api/admin/dashboard")&&method.equals("GET")){adminDashboard(e);return;}
  if(path.equals("/api/admin/movies")&&method.equals("POST")){adminMovie(e,body,false);return;}
  if(path.matches("/api/admin/movies/\\d+")&&method.equals("PUT")){adminMovie(e,body,true);return;}
  if(path.matches("/api/admin/movies/\\d+")&&method.equals("DELETE")){deactivateMovie(e,Long.parseLong(path.split("/")[4]));return;}
  if(path.equals("/api/admin/shows")&&method.equals("POST")){adminShow(e,body);return;}
  if(path.equals("/api/admin/bookings")&&method.equals("GET")){adminBookings(e);return;}
  send(e,404,Json.error("Endpoint not found"));
 }
 private void register(HttpExchange e,JsonNode b)throws Exception{
  String name=b.path("fullName").asText(), email=b.path("email").asText().trim().toLowerCase(), pw=b.path("password").asText(), phone=b.path("phone").asText("");
  if(name.isBlank()||!email.matches("^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$")||pw.length()<8){send(e,400,Json.error("Enter a valid name/email and a password of at least 8 characters."));return;}
  try(Connection c=Database.getConnection();PreparedStatement p=c.prepareStatement("INSERT INTO users(full_name,email,password_hash,phone) VALUES(?,?,?,?)")){
   p.setString(1,name);p.setString(2,email);p.setString(3,PasswordUtil.hash(pw));p.setString(4,phone);p.executeUpdate();send(e,201,Json.ok("Registration successful. You can now log in."));
  }catch(SQLIntegrityConstraintViolationException x){send(e,409,Json.error("Email is already registered."));}
 }
 private void login(HttpExchange e,JsonNode b)throws Exception{
  String email=b.path("email").asText().trim().toLowerCase(),pw=b.path("password").asText();
  try(Connection c=Database.getConnection();PreparedStatement p=c.prepareStatement("SELECT id,full_name,password_hash,role FROM users WHERE email=?")){
   p.setString(1,email);try(ResultSet r=p.executeQuery()){if(!r.next()||!PasswordUtil.verify(pw,r.getString(3))){send(e,401,Json.error("Invalid email or password."));return;}
    String token=UUID.randomUUID().toString();sessions.put(token,new Session(r.getLong(1),r.getString(4),r.getString(2)));e.getResponseHeaders().add("Set-Cookie","SESSION="+token+"; Path=/; HttpOnly; SameSite=Lax");
    ObjectNode o=Json.ok("Login successful");o.putObject("data").put("name",r.getString(2)).put("role",r.getString(4));send(e,200,o);
   }}
 }
 private Session session(HttpExchange e){String h=e.getRequestHeaders().getFirst("Cookie"); if(h==null)return null;for(String x:h.split(";")){if(x.trim().startsWith("SESSION="))return sessions.get(x.trim().substring(8));}return null;}
 private Session require(HttpExchange e,boolean admin){Session s=session(e);if(s==null||(admin&&!s.role.equals("ADMIN"))){send(e,admin?403:401,Json.error(admin?"Admin access required.":"Please log in."));return null;}return s;}
 private void logout(HttpExchange e){String h=e.getRequestHeaders().getFirst("Cookie");if(h!=null)for(String x:h.split(";"))if(x.trim().startsWith("SESSION="))sessions.remove(x.trim().substring(8));e.getResponseHeaders().add("Set-Cookie","SESSION=; Max-Age=0; Path=/");send(e,200,Json.ok("Logged out."));}
 private void movies(HttpExchange e)throws Exception{ArrayNode a=Json.M.createArrayNode();try(Connection c=Database.getConnection();PreparedStatement p=c.prepareStatement("SELECT id,title,description,duration_minutes,genre,language,certificate,poster_url,release_date FROM movies WHERE status='ACTIVE' ORDER BY release_date DESC");ResultSet r=p.executeQuery()){while(r.next()){ObjectNode o=a.addObject();o.put("id",r.getLong(1)).put("title",r.getString(2)).put("description",r.getString(3)).put("duration",r.getInt(4)).put("genre",r.getString(5)).put("language",r.getString(6)).put("certificate",r.getString(7)).put("posterUrl",r.getString(8)).put("releaseDate",String.valueOf(r.getDate(9)));}}send(e,200,a);}
 private void shows(HttpExchange e,long movieId)throws Exception{ArrayNode a=Json.M.createArrayNode();String q="SELECT s.id,t.name,sc.name,s.show_date,s.start_time,s.end_time,s.regular_price,s.premium_price,s.vip_price FROM shows s JOIN screens sc ON sc.id=s.screen_id JOIN theaters t ON t.id=sc.theater_id WHERE s.movie_id=? AND s.status='ACTIVE' AND s.show_date>=CURDATE() ORDER BY s.show_date,s.start_time";try(Connection c=Database.getConnection();PreparedStatement p=c.prepareStatement(q)){p.setLong(1,movieId);try(ResultSet r=p.executeQuery()){while(r.next()){ObjectNode o=a.addObject();o.put("id",r.getLong(1)).put("theater",r.getString(2)).put("screen",r.getString(3)).put("date",String.valueOf(r.getDate(4))).put("start",String.valueOf(r.getTime(5))).put("end",String.valueOf(r.getTime(6))).put("regular",r.getBigDecimal(7)).put("premium",r.getBigDecimal(8)).put("vip",r.getBigDecimal(9));}}}send(e,200,a);}
 private void seats(HttpExchange e,long showId)throws Exception{ArrayNode a=Json.M.createArrayNode();String q="SELECT se.id,se.seat_row,se.seat_number,se.seat_type,CASE WHEN bs.id IS NULL THEN false ELSE true END booked FROM seats se JOIN shows sh ON sh.screen_id=se.screen_id LEFT JOIN booking_seats bs ON bs.seat_id=se.id AND bs.show_id=sh.id LEFT JOIN bookings b ON b.id=bs.booking_id AND b.booking_status='CONFIRMED' WHERE sh.id=? ORDER BY se.seat_row,se.seat_number";try(Connection c=Database.getConnection();PreparedStatement p=c.prepareStatement(q)){p.setLong(1,showId);try(ResultSet r=p.executeQuery()){while(r.next()){ObjectNode o=a.addObject();o.put("id",r.getLong(1)).put("label",r.getString(2)+r.getInt(3)).put("row",r.getString(2)).put("number",r.getInt(3)).put("type",r.getString(4)).put("booked",r.getBoolean(5));}}}send(e,200,a);}
 private void createBooking(HttpExchange e,JsonNode b)throws Exception{Session s=require(e,false);if(s==null)return;long show=b.path("showId").asLong();ArrayNode ids=(ArrayNode)b.path("seatIds");if(show==0||ids==null||ids.isEmpty()){send(e,400,Json.error("Select a show and at least one seat."));return;}
  try(Connection c=Database.getConnection()){c.setAutoCommit(false);try{
   PreparedStatement sp=c.prepareStatement("SELECT sh.screen_id,sh.regular_price,sh.premium_price,sh.vip_price FROM shows sh WHERE sh.id=? AND sh.status='ACTIVE' FOR UPDATE");sp.setLong(1,show);ResultSet sr=sp.executeQuery();if(!sr.next()){c.rollback();send(e,404,Json.error("Show not found."));return;}long screen=sr.getLong(1);var prices=new java.math.BigDecimal[]{sr.getBigDecimal(2),sr.getBigDecimal(3),sr.getBigDecimal(4)};
   String ref="BK-"+UUID.randomUUID().toString().substring(0,8).toUpperCase();java.math.BigDecimal total=java.math.BigDecimal.ZERO;List<Long> seatList=new ArrayList<>();
   for(JsonNode n:ids){long sid=n.asLong();PreparedStatement q=c.prepareStatement("SELECT seat_type FROM seats WHERE id=? AND screen_id=?");q.setLong(1,sid);q.setLong(2,screen);ResultSet rr=q.executeQuery();if(!rr.next())throw new IllegalArgumentException("Invalid seat.");int idx=switch(rr.getString(1)){case "PREMIUM"->1;case "VIP"->2;default->0;};PreparedStatement z=c.prepareStatement("SELECT id FROM booking_seats WHERE show_id=? AND seat_id=?");z.setLong(1,show);z.setLong(2,sid);if(z.executeQuery().next())throw new IllegalStateException("One or more selected seats are no longer available.");seatList.add(sid);total=total.add(prices[idx]);}
   PreparedStatement bi=c.prepareStatement("INSERT INTO bookings(booking_reference,user_id,show_id,total_amount) VALUES(?,?,?,?)",Statement.RETURN_GENERATED_KEYS);bi.setString(1,ref);bi.setLong(2,s.userId);bi.setLong(3,show);bi.setBigDecimal(4,total);bi.executeUpdate();ResultSet k=bi.getGeneratedKeys();k.next();long bid=k.getLong(1);
   PreparedStatement si=c.prepareStatement("INSERT INTO booking_seats(booking_id,show_id,seat_id,price) VALUES(?,?,?,?)");for(long sid:seatList){PreparedStatement q=c.prepareStatement("SELECT seat_type FROM seats WHERE id=?");q.setLong(1,sid);ResultSet rr=q.executeQuery();rr.next();int idx=switch(rr.getString(1)){case "PREMIUM"->1;case "VIP"->2;default->0;};si.setLong(1,bid);si.setLong(2,show);si.setLong(3,sid);si.setBigDecimal(4,prices[idx]);si.addBatch();}si.executeBatch();c.commit();
   ObjectNode o=Json.ok("Booking created successfully.");o.putObject("data").put("id",bid).put("reference",ref).put("total",total);send(e,201,o);
  }catch(Exception x){c.rollback();int status=x instanceof IllegalStateException?409:400;send(e,status,Json.error(x.getMessage()));}}
 }
 private void bookings(HttpExchange e)throws Exception{Session s=require(e,false);if(s==null)return;String q="SELECT b.id,b.booking_reference,m.title,sh.show_date,sh.start_time,b.total_amount,b.booking_status,b.booked_at,GROUP_CONCAT(CONCAT(se.seat_row,se.seat_number) ORDER BY se.seat_row,se.seat_number) FROM bookings b JOIN shows sh ON sh.id=b.show_id JOIN movies m ON m.id=sh.movie_id LEFT JOIN booking_seats bs ON bs.booking_id=b.id LEFT JOIN seats se ON se.id=bs.seat_id WHERE b.user_id=? GROUP BY b.id ORDER BY b.booked_at DESC";ArrayNode a=Json.M.createArrayNode();try(Connection c=Database.getConnection();PreparedStatement p=c.prepareStatement(q)){p.setLong(1,s.userId);ResultSet r=p.executeQuery();while(r.next()){ObjectNode o=a.addObject();o.put("id",r.getLong(1)).put("reference",r.getString(2)).put("movie",r.getString(3)).put("date",String.valueOf(r.getDate(4))).put("time",String.valueOf(r.getTime(5))).put("amount",r.getBigDecimal(6)).put("status",r.getString(7)).put("bookedAt",String.valueOf(r.getTimestamp(8))).put("seats",r.getString(9));}}send(e,200,a);}
 private void cancel(HttpExchange e,long id)throws Exception{Session s=require(e,false);if(s==null)return;try(Connection c=Database.getConnection();PreparedStatement p=c.prepareStatement("UPDATE bookings SET booking_status='CANCELLED',cancelled_at=NOW() WHERE id=? AND user_id=? AND booking_status='CONFIRMED'")){p.setLong(1,id);p.setLong(2,s.userId);if(p.executeUpdate()==0){send(e,409,Json.error("Booking cannot be cancelled."));return;}send(e,200,Json.ok("Booking cancelled."));}}
 private void adminDashboard(HttpExchange e)throws Exception{if(require(e,true)==null)return;ObjectNode o=Json.ok("Dashboard");ObjectNode d=o.putObject("data");try(Connection c=Database.getConnection()){for(String x:new String[]{"users","movies","shows","bookings"}){try(Statement st=c.createStatement();ResultSet r=st.executeQuery("SELECT COUNT(*) FROM "+x)){r.next();d.put(x,r.getLong(1));}}try(Statement st=c.createStatement();ResultSet r=st.executeQuery("SELECT COALESCE(SUM(total_amount),0) FROM bookings WHERE booking_status='CONFIRMED'")){r.next();d.put("revenue",r.getBigDecimal(1));}}send(e,200,o);}
 private void adminMovie(HttpExchange e,JsonNode b,boolean update)throws Exception{if(require(e,true)==null)return;String sql=update?"UPDATE movies SET title=?,description=?,duration_minutes=?,genre=?,language=?,certificate=?,poster_url=?,release_date=? WHERE id=?":"INSERT INTO movies(title,description,duration_minutes,genre,language,certificate,poster_url,release_date) VALUES(?,?,?,?,?,?,?,?)";try(Connection c=Database.getConnection();PreparedStatement p=c.prepareStatement(sql)){int i=1;p.setString(i++,b.path("title").asText());p.setString(i++,b.path("description").asText());p.setInt(i++,b.path("duration").asInt());p.setString(i++,b.path("genre").asText());p.setString(i++,b.path("language").asText());p.setString(i++,b.path("certificate").asText());p.setString(i++,b.path("posterUrl").asText());p.setDate(i++,java.sql.Date.valueOf(b.path("releaseDate").asText()));if(update)p.setLong(i,b.path("id").asLong());p.executeUpdate();send(e,update?200:201,Json.ok(update?"Movie updated.":"Movie created."));}}
 private void deactivateMovie(HttpExchange e,long id)throws Exception{if(require(e,true)==null)return;try(Connection c=Database.getConnection();PreparedStatement p=c.prepareStatement("UPDATE movies SET status='INACTIVE' WHERE id=?")){p.setLong(1,id);p.executeUpdate();send(e,200,Json.ok("Movie deactivated."));}}
 private void adminShow(HttpExchange e,JsonNode b)throws Exception{if(require(e,true)==null)return;String q="INSERT INTO shows(movie_id,screen_id,show_date,start_time,end_time,regular_price,premium_price,vip_price) VALUES(?,?,?,?,?,?,?,?)";try(Connection c=Database.getConnection();PreparedStatement p=c.prepareStatement(q)){p.setLong(1,b.path("movieId").asLong());p.setLong(2,b.path("screenId").asLong());p.setDate(3,Date.valueOf(b.path("date").asText()));p.setTime(4,Time.valueOf(b.path("start").asText()));p.setTime(5,Time.valueOf(b.path("end").asText()));p.setBigDecimal(6,b.path("regular").decimalValue());p.setBigDecimal(7,b.path("premium").decimalValue());p.setBigDecimal(8,b.path("vip").decimalValue());p.executeUpdate();send(e,201,Json.ok("Show created."));}}
 private void adminBookings(HttpExchange e)throws Exception{if(require(e,true)==null)return;ArrayNode a=Json.M.createArrayNode();String q="SELECT b.booking_reference,u.full_name,m.title,sh.show_date,sh.start_time,b.total_amount,b.booking_status FROM bookings b JOIN users u ON u.id=b.user_id JOIN shows sh ON sh.id=b.show_id JOIN movies m ON m.id=sh.movie_id ORDER BY b.booked_at DESC";try(Connection c=Database.getConnection();Statement p=c.createStatement();ResultSet r=p.executeQuery(q)){while(r.next()){ObjectNode o=a.addObject();o.put("reference",r.getString(1)).put("customer",r.getString(2)).put("movie",r.getString(3)).put("date",String.valueOf(r.getDate(4))).put("time",String.valueOf(r.getTime(5))).put("amount",r.getBigDecimal(6)).put("status",r.getString(7));}}send(e,200,a);}
 private void staticFile(HttpExchange e)throws IOException{String p=e.getRequestURI().getPath();if(p.equals("/"))p="/index.html";if(p.startsWith("/api/")){send(e,404,Json.error("Not found"));return;}File f=new File("src/main/webapp"+p);if(!f.exists()||f.isDirectory()){sendText(e,404,"Not found");return;}String ct=p.endsWith(".html")?"text/html":p.endsWith(".css")?"text/css":"application/javascript";e.getResponseHeaders().set("Content-Type",ct+";charset=UTF-8");byte[] b=java.nio.file.Files.readAllBytes(f.toPath());e.sendResponseHeaders(200,b.length);try(OutputStream o=e.getResponseBody()){o.write(b);}}
 private static void send(HttpExchange e,int code,Object body){try{sendText(e,code,Json.M.writeValueAsString(body));}catch(Exception ignored){}}
 private static void sendText(HttpExchange e,int code,String body){try{byte[] b=body.getBytes(StandardCharsets.UTF_8);e.sendResponseHeaders(code,b.length);try(OutputStream o=e.getResponseBody()){o.write(b);}}catch(IOException ignored){}}
}
