CREATE DATABASE IF NOT EXISTS theater_booking CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE theater_booking;

CREATE TABLE users (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 full_name VARCHAR(120) NOT NULL,
 email VARCHAR(190) NOT NULL UNIQUE,
 password_hash VARCHAR(500) NOT NULL,
 phone VARCHAR(30),
 role ENUM('CUSTOMER','ADMIN') NOT NULL DEFAULT 'CUSTOMER',
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE movies (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 title VARCHAR(200) NOT NULL, description TEXT, duration_minutes INT NOT NULL,
 genre VARCHAR(100), language VARCHAR(60), certificate VARCHAR(20),
 poster_url VARCHAR(500), trailer_url VARCHAR(500), release_date DATE,
 status ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 INDEX idx_movies_status(status)
);
CREATE TABLE theaters (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(150) NOT NULL, location VARCHAR(255) NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE screens (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, theater_id BIGINT NOT NULL, name VARCHAR(100) NOT NULL,
 total_rows INT NOT NULL, total_columns INT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT fk_screen_theater FOREIGN KEY(theater_id) REFERENCES theaters(id) ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE TABLE seats (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, screen_id BIGINT NOT NULL, seat_row VARCHAR(10) NOT NULL,
 seat_number INT NOT NULL, seat_type ENUM('REGULAR','PREMIUM','VIP') NOT NULL DEFAULT 'REGULAR',
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 UNIQUE KEY uq_screen_seat(screen_id, seat_row, seat_number),
 FOREIGN KEY(screen_id) REFERENCES screens(id) ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE TABLE shows (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, movie_id BIGINT NOT NULL, screen_id BIGINT NOT NULL,
 show_date DATE NOT NULL, start_time TIME NOT NULL, end_time TIME NOT NULL,
 regular_price DECIMAL(10,2) NOT NULL, premium_price DECIMAL(10,2) NOT NULL, vip_price DECIMAL(10,2) NOT NULL,
 status ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(movie_id) REFERENCES movies(id) ON DELETE RESTRICT ON UPDATE CASCADE,
 FOREIGN KEY(screen_id) REFERENCES screens(id) ON DELETE RESTRICT ON UPDATE CASCADE,
 INDEX idx_show_movie_date(movie_id,show_date), INDEX idx_show_screen_date(screen_id,show_date)
);
CREATE TABLE bookings (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, booking_reference VARCHAR(40) NOT NULL UNIQUE,
 user_id BIGINT NOT NULL, show_id BIGINT NOT NULL, total_amount DECIMAL(10,2) NOT NULL,
 booking_status ENUM('CONFIRMED','CANCELLED','EXPIRED') NOT NULL DEFAULT 'CONFIRMED',
 booked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, cancelled_at TIMESTAMP NULL,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE CASCADE,
 FOREIGN KEY(show_id) REFERENCES shows(id) ON DELETE RESTRICT ON UPDATE CASCADE,
 INDEX idx_booking_user(user_id), INDEX idx_booking_show(show_id)
);
CREATE TABLE booking_seats (
 id BIGINT PRIMARY KEY AUTO_INCREMENT, booking_id BIGINT NOT NULL, show_id BIGINT NOT NULL,
 seat_id BIGINT NOT NULL, price DECIMAL(10,2) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 UNIQUE KEY uq_show_seat(show_id,seat_id),
 FOREIGN KEY(booking_id) REFERENCES bookings(id) ON DELETE RESTRICT ON UPDATE CASCADE,
 FOREIGN KEY(show_id) REFERENCES shows(id) ON DELETE RESTRICT ON UPDATE CASCADE,
 FOREIGN KEY(seat_id) REFERENCES seats(id) ON DELETE RESTRICT ON UPDATE CASCADE
);
