const $=s=>document.querySelector(s), api=async(u,o={})=>{const r=await fetch(u,{credentials:"include",headers:{"Content-Type":"application/json"},...o});const d=await r.json();if(!r.ok)throw Error(d.message||"Request failed");return d};
document.addEventListener("DOMContentLoaded",async()=>{
 if($("#movieGrid")){try{const m=await api("/api/movies");$("#movieGrid").innerHTML=m.map(x=>`<article class="card"><img src="${x.posterUrl||''}" alt=""><h3>${x.title}</h3><p>${x.genre} • ${x.language} • ${x.duration} min</p><p>${x.description||""}</p><a class="btn" href="/movie-details.html?id=${x.id}">Book Now</a></article>`).join("")}catch(e){$("#movieGrid").textContent=e.message}}
 if($("#login"))$("#login").onsubmit=async e=>{e.preventDefault();try{const b=Object.fromEntries(new FormData(e.target));const d=await api("/api/auth/login",{method:"POST",body:JSON.stringify(b)});location.href=d.data.role==="ADMIN"?"/admin/dashboard.html":"/"}catch(x){$("#msg").textContent=x.message}};
 if($("#register"))$("#register").onsubmit=async e=>{e.preventDefault();try{await api("/api/auth/register",{method:"POST",body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});location.href="/login.html"}catch(x){$("#msg").textContent=x.message}};
 if($("#shows")){const id=new URLSearchParams(location.search).get("id");try{const ms=await api("/api/movies");const m=ms.find(x=>x.id==id);$("#movieInfo").innerHTML=`<h1>${m.title}</h1><p>${m.genre} • ${m.language} • ${m.duration} min</p><p>${m.description||""}</p>`;const s=await api(`/api/movies/${id}/shows`);$("#shows").innerHTML=s.map(x=>`<div class="show"><div><b>${x.theater} — ${x.screen}</b><br>${x.date} • ${x.start}</div><a class="btn" href="/seats.html?show=${x.id}">₹${x.regular} • Select</a></div>`).join("")||"<p>No upcoming shows.</p>"}catch(x){$("#shows").textContent=x.message}}
 if($("#seatMap")){const id=new URLSearchParams(location.search).get("show"), chosen=[];try{const s=await api(`/api/shows/${id}/seats`);$("#seatMap").innerHTML=s.map(x=>`<button class="seat ${x.booked?"booked":""}" data-id="${x.id}" data-label="${x.label}" ${x.booked?"disabled":""}>${x.label}</button>`).join("");document.querySelectorAll(".seat:not(.booked)").forEach(b=>b.onclick=()=>{const i=chosen.indexOf(+b.dataset.id);if(i>=0){chosen.splice(i,1);b.classList.remove("selected")}else{chosen.push(+b.dataset.id);b.classList.add("selected")}$("#selected").textContent=chosen.map(i=>document.querySelector(`[data-id="${i}"]`).dataset.label).join(", ")||"None";$("#total").textContent="Calculated at checkout"});$("#book").onclick=async()=>{try{const d=await api("/api/bookings",{method:"POST",body:JSON.stringify({showId:+id,seatIds:chosen})});location.href="/booking-confirmation.html?ref="+d.data.reference}catch(x){$("#msg").textContent=x.message}}}catch(x){$("#msg").textContent=x.message}}
 if($("#bookings")){try{const b=await api("/api/bookings");$("#bookings").innerHTML=b.map(x=>`<div class="card"><b>${x.reference}</b><h3>${x.movie}</h3><p>${x.date} • ${x.time} • Seats: ${x.seats||"-"}</p><p>₹${x.amount} • ${x.status}</p>${x.status==="CONFIRMED"?`<button class="btn" onclick="cancelBooking(${x.id})">Cancel</button>`:""}</div>`).join("")||"<p>No bookings yet.</p>"}catch(x){$("#bookings").textContent=x.message}}
 if($("#ref"))$("#ref").textContent=new URLSearchParams(location.search).get("ref")||"Confirmed";
 if($("#stats")){try{const d=(await api("/api/admin/dashboard")).data;$("#stats").innerHTML=[["Users",d.users],["Movies",d.movies],["Shows",d.shows],["Bookings",d.bookings],["Revenue","₹"+d.revenue]].map(x=>`<div class="stat"><small>${x[0]}</small><h2>${x[1]}</h2></div>`).join("");const b=await api("/api/admin/bookings");$("#adminBookings").innerHTML=b.map(x=>`<div class="card"><b>${x.reference}</b> — ${x.customer}<br>${x.movie} • ${x.date} ${x.time} • ₹${x.amount} • ${x.status}</div>`).join("")}catch(x){$("#stats").textContent=x.message}}
});
async function cancelBooking(id){if(!confirm("Cancel this booking?"))return;try{await api(`/api/bookings/${id}/cancel`,{method:"POST"});location.reload()}catch(e){alert(e.message)}}
